const mockedPeople = [
  {
    id: 0,
    name: "John",
    lastName: "Doe",
    email: "john-doe@john.doe",
    phoneNumber: "+1 512 829 8700",
    status: true,
  },
  {
    id: 1,
    name: "Bob",
    lastName: "Doe",
    email: "john-doe@bob.doe",
    phoneNumber: "+1 512 819 8700",
    status: false,
  },
  {
    id: 2,
    name: "Jim",
    lastName: "Doe",
    email: "john-doe@jim.doe",
    phoneNumber: "+1 512 829 3700",
    status: true,
  },
  {
    id: 3,
    name: "Jessica",
    lastName: "Doe",
    email: "john-doe@jessi.doe",
    phoneNumber: "+2 512 819 8700",
    status: false,
  },
  {
    id: 4,
    name: "John",
    lastName: "Doe",
    email: "john-doe@john.doe",
    phoneNumber: "+1 512 829 8700",
    status: true,
  },
  {
    id: 5,
    name: "Bob",
    lastName: "Doe",
    email: "john-doe@bob.doe",
    phoneNumber: "+1 512 819 8700",
    status: false,
  },
  {
    id: 6,
    name: "Jim",
    lastName: "Doe",
    email: "john-doe@jim.doe",
    phoneNumber: "+1 512 829 3700",
    status: true,
  },
  {
    id: 7,
    name: "Jessica",
    lastName: "Doe",
    email: "john-doe@jessi.doe",
    phoneNumber: "+2 512 819 8700",
    status: false,
  },
  {
    id: 8,
    name: "John",
    lastName: "Doe",
    email: "john-doe@john.doe",
    phoneNumber: "+1 512 829 8700",
    status: true,
  },
  {
    id: 9,
    name: "Bob",
    lastName: "Doe",
    email: "john-doe@bob.doe",
    phoneNumber: "+1 512 819 8700",
    status: false,
  },
  {
    id: 10,
    name: "Jim",
    lastName: "Doe",
    email: "john-doe@jim.doe",
    phoneNumber: "+1 512 829 3700",
    status: true,
  },
  {
    id: 11,
    name: "Jessica",
    lastName: "Doe",
    email: "john-doe@jessi.doe",
    phoneNumber: "+2 512 819 8700",
    status: false,
  },
  {
    id: 12,
    name: "John",
    lastName: "Doe",
    email: "john-doe@john.doe",
    phoneNumber: "+1 512 829 8700",
    status: true,
  },
  {
    id: 13,
    name: "Bob",
    lastName: "Doe",
    email: "john-doe@bob.doe",
    phoneNumber: "+1 512 819 8700",
    status: false,
  },
  {
    id: 14,
    name: "Jim",
    lastName: "Doe",
    email: "john-doe@jim.doe",
    phoneNumber: "+1 512 829 3700",
    status: true,
  },
  {
    id: 15,
    name: "Jessica",
    lastName: "Doe",
    email: "john-doe@jessi.doe",
    phoneNumber: "+2 512 819 8700",
    status: false,
  },
  {
    id: 16,
    name: "John",
    lastName: "Doe",
    email: "john-doe@john.doe",
    phoneNumber: "+1 512 829 8700",
    status: true,
  },
  {
    id: 17,
    name: "Bob",
    lastName: "Doe",
    email: "john-doe@bob.doe",
    phoneNumber: "+1 512 819 8700",
    status: false,
  },
  {
    id: 18,
    name: "Jim",
    lastName: "Doe",
    email: "john-doe@jim.doe",
    phoneNumber: "+1 512 829 3700",
    status: true,
  },
  {
    id: 19,
    name: "Jessica",
    lastName: "Doe",
    email: "john-doe@jessi.doe",
    phoneNumber: "+2 512 819 8700",
    status: false,
  },
];

export default mockedPeople;
